import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Topbar from "../../components/shared/Topbar";
import LeftSidebar from "../../components/shared/LeftSidebar";
import RightSidebar from "../../components/shared/RightSidebar"
import Bottombar from "../../components/shared/Bottombar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased bg-black h-8/12` }
      >
        <Topbar/>
        <main className=" flex flex-grow-0 h-8/12">
          

          <LeftSidebar/>
          <section className="w-8/12  h-8/12">
            <div className="h-8/12">
              {children}
            </div>
          </section>
        </main>
        <Bottombar/>
      </body>
    </html>
    </ClerkProvider>
  );
}
